name: hosptel_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: 6.1.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  bloc: ^8.1.4
  intl: ^0.19.0
  flutter_bloc: ^8.1.5
  flutter_file_downloader: ^2.0.0
  dartz: ^0.10.1
  http: ^1.1.0
  equatable: ^2.0.0
  get_it: ^7.6.4
  internet_connection_checker: ^1.0.0+1
  rename: ^3.0.2
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  dropdown_button2: ^2.3.8
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  curved_labeled_navigation_bar: ^2.0.2 
  stroke_text: any
  logger: ^2.2.0
  double_back_to_exit: ^1.0.0
  pin_code_fields: ^8.0.1
  jwt_decoder: ^2.0.1 
  shimmer: ^3.0.0
  toastification: ^2.3.0
dev_dependencies:
  
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  
  assets:
      - assets/image/png/
      - assets/image/svg/

  

  # example:
  fonts:
    - family: ExtraBold
      fonts:
        - asset: assets/fonts/Tajawal-ExtraBold.ttf 

    - family: TajawalLight
      fonts:
        - asset: assets/fonts/Tajawal-Light.ttf 

    - family: TajawalRegular
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf 
    
    - family: TajawalMedium
      fonts:
        - asset: assets/fonts/Tajawal-Medium.ttf  
    
    - family: TajawalBold
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf

     
          
    
